### ISSUE TITLE
Create indexer for fetch transaction

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuel-explorer#17]
[FRO-29](https://linear.app/fuel-network/issue/FRO-29/create-indexer-for-fetch-transaction)

Fetch a single TX should fetch all the fields available on the TX this is one example [https://gist.github.com/luizstacio/44bda679b8805bbb835370f839855227](https://gist.github.com/luizstacio/44bda679b8805bbb835370f839855227)

**Comment by Braqzen** [comment]
What is the difference between this and #12?
Ofc, this one has a lot more data, which at the moment is an issue, but we can expand the amount of data gathered in the linked issue later.
