### ISSUE TITLE
Responsive fix on Bridge UI

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuel-explorer#211]
some extra right space when using Iphone 12 in chrome inspector

problem happens when you are in a popup. If you remove the blur you can see the background layout is broken

![Image](https://github.com/FuelLabs/fuel-explorer/assets/8636507/7cc840bd-5d34-434f-ac4d-711c01449b2f)

**Comment by xlzy905** [comment]
can i fix？

**Comment by LuizAsFight** [comment]
yes please @xlzy905 


thanks !

**Comment by xlzy905** [comment]
Hey. I would like to share my survey results here

Debugging in mobile mode on a PC browser. When a pop-up window appears, radix-ui will add a padding right attribute to the body tag, which can cause layout issues after the pop-up window appears

![image](https://github.com/FuelLabs/fuel-explorer/assets/86589034/4f84691f-8235-4352-988e-3b6611921626)

But when opened on a real phone, there will be no corresponding situation. This is related to the logic of responsive judgment

So I think this issue should not have appeared in real scenarios and can be ignored

**Comment by LuizAsFight** [comment]
@xlzy905 I see the behavior looking on my phone, even without popup opened. there is a horizontal scroll that shows we have extra space

**Comment by skushagra9** [comment]
Hi, I have checked, this and I think this issue is solved.
Let me know if its not solved, I would like to take this up

**Comment by LuizAsFight** [comment]
yes it's fixed @skushagra9 🙏🏻
