### ISSUE TITLE
Navigation issue (404) in explorer UI

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuel-explorer#212]
we keep getting this screen sometimes

two situations I was able to simulate:
- being on bridge, and click on "explorer" link on menu
- being on explorer home, and click on first "mint" transaction of the list

![Image](https://github.com/FuelLabs/fuel-explorer/assets/8636507/d1b76db5-ffb0-45ad-a078-946b03ce86d2)

**Comment by helciofranco** [comment]
It looks like this has been fixed. I didn't find a way to reproduce it.
