### ISSUE TITLE
Chrome & macOS slowing to a halt while the bridge is "working"

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuel-explorer#221]
ProductName: macOS
ProductVersion: 14.3.1
BuildVersion: 23D60
Google Chrome: Version 122.0.6261.69 (Official Build) (x86_64)

![image](https://github.com/FuelLabs/fuel-bridge/assets/114662397/6ae1eaaf-ce1b-48dc-b9cf-fa35baec343c)

While the Bridge is in the settlement phase (shown above) or the Confirm transaction phase while it's open and on the screen, it's using so many of my machine's resources that Chrome becomes unusable and eventually the whole machine becomes unusable.

Let me know if you need more information.

**Comment by helciofranco** [comment]
Thanks @DefiCake @HoTandy 
I've just moved to the [fuel-explorer](https://github.com/FuelLabs/fuel-explorer).

**Comment by helciofranco** [comment]
@HoTandy this fix has been released on `next` version.
