### ISSUE TITLE
Standardising Chain and Copy icons across Fuel

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuel-explorer#227]
After some discussion on [Slack](https://fuellabs.slack.com/archives/C04MA809YC9/p1710252570011369) with @LuizAsFight, it was recommended I raise this issue.

Across the wallet and the bridge and other places where we see transaction IDs and addresses, define and find a common standard with what you can do with the transaction ID or address and whether the link will open an external link or not.  In the wallet you can copy an address using the copy icon.  In the bridge there's a chain image (icon) next to the transaction ID highlighting that it's a link. With a link it's clear that it's a link, so maybe it's best to always have the copy icon/image next to the link so the user can copy the address or transaction ID. 

Generally speaking the following should be taken into consideration:

- When clicking on a link, should it open there or open in a new tab?
- Do we continue to use the chain link icon when the link links to an external site like etherscan?
- If it's an internal link, do we simply use the copy icon next to the link like we see in the fuel wallet and fuel explorer.

In the following image we see a copy icon next to the addresses/transaction IDs

![image](https://github.com/FuelLabs/fuel-explorer/assets/114662397/607f2d13-58ea-4881-ab9a-b3d536033a9b)

The following image shows the chain icon and clicking on the link will direct to etherscan

![image](https://github.com/FuelLabs/fuel-explorer/assets/114662397/4ca47808-5963-4329-8d21-edb78a4eadcf)

The following image is a transaction from Fuel to an external wallet, but it also shows a chain link icon.  Maybe this should be a copy icon as it will open the internal Fuel explorer and not an external site.

![image](https://github.com/FuelLabs/fuel-explorer/assets/114662397/cd127d0d-dab2-4446-9749-278ee38389cf)

The following image also shows copy icons next to the fuel addresses as they're internal addresses.

![image](https://github.com/FuelLabs/fuel-explorer/assets/114662397/111eb023-b6e8-4f64-944b-ca31888cd2b2)

**Comment by HoTandy** [comment]
I've found more examples of inconsistencies this time from within the wallet.  I've circled the 3 icons which do slightly different things to what we discussed on slack.

<img width="704" alt="image" src="https://github.com/FuelLabs/fuel-explorer/assets/114662397/61239b33-6463-471f-931b-cdcbd92e1005">

1) Clicking on this copies the transaction ID 0xcae664b7a7f8f4cd19ed3c4232b3a1d52fcdf798b36e99e9a29ff0f7235e7c0c
2) Clicking on this copies the transaction URL https://app.fuel.network/tx/0xcae664b7a7f8f4cd19ed3c4232b3a1d52fcdf798b36e99e9a29ff0f7235e7c0c
3) Clicking on this opens the transaction in the Fuel Explorer

In the bridge, clicking on the chain icon does not do a copy, it's just an image.

**Comment by gww-fuel** [comment]
I am looking forward for more total end2end tests, that I can run with one command on my computer , like `docker-compose up` or whatever else serving purpose :crossed_fingers:

**Comment by LuizAsFight** [comment]
@gww-fuel e2e tests are enabled on bridge again. its not a 1 command thing but its also not hard to do

you need to:
1- clone repo
2- create .env files in the packages folders (just copy paste .env.example)
3- run `pnpm install`
4- run `pnpm node:start`
5- run `pnpm test:e2e`

**Comment by HoTandy** [comment]
For creating the `.env` files, see this comment (docs need changing) https://github.com/FuelLabs/fuel-explorer/issues/222#issuecomment-2017505914

**Comment by LuizAsFight** [comment]
this will not be prioritized as it's a default behavior from design system
