### ISSUE TITLE
Broken transaction link from bridge

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuel-explorer#228]
Create a withdraw transaction in the bridge, while it's in the `Settlement` phase as shown below...

![image](https://github.com/FuelLabs/fuel-explorer/assets/114662397/e1da4487-f574-44b9-bd5e-36af4d475250)

...click on the ID, the link is broken and takes you to a 404 as shown below.

![image](https://github.com/FuelLabs/fuel-explorer/assets/114662397/acc2a6f2-bf69-45fc-8ec7-ce3603ea9604)

The link seems to be constructed as an `undefinedtx` in the URL

[https://next-app.fuel.network/bridge/undefinedtx/0xe54ce34c58885fd1b9b3747c184c7c4755b632e0dbdf9b8d3cabc8866a57edfa](https://next-app.fuel.network/bridge/undefinedtx/0xe54ce34c58885fd1b9b3747c184c7c4755b632e0dbdf9b8d3cabc8866a57edfa)

The transaction does exist if I construct the URL properly

[https://next-app.fuel.network/tx/0xe54ce34c58885fd1b9b3747c184c7c4755b632e0dbdf9b8d3cabc8866a57edfa/simple](https://next-app.fuel.network/tx/0xe54ce34c58885fd1b9b3747c184c7c4755b632e0dbdf9b8d3cabc8866a57edfa/simple)

**Comment by helciofranco** [comment]
Hi @richardgreg that sounds good.
Can you open a PR for this issue?
