### ISSUE TITLE
possibly abandoned project pages

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuel-explorer#253]
The following projects on https://next-app.fuel.network/ecosystem look abandoned or dead.

https://baldboyznft.com/
unic/nufutu
Ruscet - leads to an empty github page
https://zapinfra.com/

It might be best to remove them.

**Comment by helciofranco** [comment]
@Rubyt0x Could you help us with this issue?

**Comment by Rubyt0x** [comment]
Interesting, yes I can check with the projects

**Comment by Rubyt0x** [comment]
The Zap website is being migrated to another host provider, so it will be live again soon

**Comment by Rubyt0x** [comment]
Fixed the others though
