### ISSUE TITLE
Add pagination+sorting to "Account Transactions" page

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuel-explorer#331]
blocked by #330 

should show latest first.

**Comment by Chester-King** [comment]
Raised this issue on the fuel forum for community to try a hand at this - https://forum.fuel.network/t/transactions-shown-in-explorer-are-not-sorted-accordingly/6159 
@LuizAsFight @pedronauck if work on this fix hasn't started yet - would love to assist you guys with this issue

**Comment by LuizAsFight** [comment]
@Chester-King we need a better data structure to be able to accomplish this issue. team is working on https://github.com/FuelLabs/fuel-explorer/issues/408
after this is unblocked, we will work on this issue and any help is appreciated, thanks!

**Comment by LuizAsFight** [comment]
Closed by #375
