### ISSUE TITLE
Toast bugged on start deposit / withdraw

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuel-explorer#337]
- it's behind the dialog background blur

**Comment by xlzy905** [comment]
Is this toast?
![image](https://github.com/FuelLabs/fuel-explorer/assets/86589034/adcaee36-c900-4139-ab6a-432149418f42)

It seems to be caused by hierarchy. Can I try to fix it?

**Comment by LuizAsFight** [comment]
hello @xlzy905 , yes please :) thank you
