### ISSUE TITLE
Unite some frontend repositories

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuel-explorer#340]
we currently have many repos which makes hard to be updating and changing versions across them, bringing lots of overhead work in our development cycle

current repos are: 
`fuels-wallet` `fuels-npm-packs` `fuel-connectors` `fuel-explorer`

this issues proposes to unite following repos, migrating them to live inside `fuel-explorer` in the format of new packages
- fuels-wallet
- fuels-npm-packs

after this change, frontend stack will have only this repos:
- fuel-connectors
- fuel-explorer

benefits:
- single place to update our stack to new sway, fuel-core, TS SDK, etc... 
- remove overhead of releasing versions and updating it on other repos all the time

disadvantage:
- effort for fine-tuning on CI side

PS:
- make sure we disable deprecated any `npm` packages that will not be maintained anymore

**Comment by luizstacio** [comment]
Should we consider the update from the old UI library to the new one before/after this migration?

**Comment by LuizAsFight** [comment]
good point @luizstacio we can split the work:
- first migrate `fuels-npm-packs` , which doesn't depend on the old UI
- then migrate `fuels-wallet`, and migrate to the new `fuels/ui` together. by doing this we 100% get rid of the legacy UI
