### ISSUE TITLE
Update to radix v3

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuel-explorer#354]
This is needed to get new features from radix, and also keep updated to last version

As we are gonna need to change the design system, it's good to be already updated to avoid future breaking changes

https://www.radix-ui.com/blog/themes-3

**Comment by arthurgeron** [comment]
Blocked due to [lack of customization](https://github.com/radix-ui/themes/issues/521) & breaking changes on RT Input (removal of `Input.Field` component).
