### ISSUE TITLE
connect L1 indexer to fetch contract logs for the bridge

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuel-explorer#379]
conclude the work started before by @helciofranco

**Comment by helciofranco** [comment]
@LuizAsFight don't need to answer, just pinging you to confirm that you've closed it intentionally

**Comment by LuizAsFight** [comment]
yes @helciofranco closed in favor or https://github.com/FuelLabs/fuel-explorer/issues/267
