### ISSUE TITLE
toast is taking too long too appear

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuel-explorer#397]
after you submit a transacation there is a toast saying "you can close the popup...."

RN it's taking too long to appear, only after we get the receipts. Instead, It should appear as soon as the transaction is submitted

**Comment by arthurgeron** [comment]
This should've been already fixed in #394

**Comment by LuizAsFight** [comment]
yes @arthurgeron it's already archived in the project. I am also closing it, thanks
