### ISSUE TITLE
Create Advanced Tab on Transaction Page

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuel-explorer#66]
The advanced tab should show the following;
- The raw payload of a transaction; 
- And the whole query from the transaction in JSON. The JSON should be only the transaction, not the props from the GraphQL.

GraphQL query: https://gist.github.com/luizstacio/a5e51705a8965a3ece87cea90981fa15
Design: https://www.figma.com/file/VTWcuPxsUtKZDk0iKn3y7T/Fuel-Portal-Product-Board?type=design&node-id=2068-72541&mode=design&t=QvLFwOte6x138asK-4

**Comment by LuizAsFight** [comment]
done in #77
