### ISSUE TITLE
Block Page -> Advanced

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuel-explorer#92]
The advanced view of a block should show the whole query from the block including the transactions (id, type, timestamp, and status) in JSON. The JSON should be only the block, not the props from the GraphQL.

Design: https://www.figma.com/file/VTWcuPxsUtKZDk0iKn3y7T/Fuel-Portal-Product-Board?type=design&node-id=2068-72552&mode=design&t=S2Jr6aSBRekhoQju-4

**Comment by matt-user** [comment]
closed by https://github.com/FuelLabs/fuel-explorer/pull/98
